"""
AgroResilience - Crop Database
Comprehensive agronomic database for 24+ crops with rotation properties,
water needs, climate preferences, and disease break families.
"""

CROPS_DATABASE = [
    {
        "id": "rice",
        "name": "Rice (Paddy)",
        "bangla_name": "ধান (Paddy)",
        "scientific_name": "Oryza sativa",
        "category": "Cereal",
        "family": "Poaceae",
        "water_requirement_mm": 1200,
        "water_level": "High",
        "temp_min": 20,
        "temp_max": 35,
        "optimal_temp": "22°C - 32°C",
        "soil_types": ["Clay", "Loamy", "Silty", "Mixed"],
        "soil_ph_range": [5.5, 7.0],
        "nutrient_demand": {"N": "High", "P": "Medium", "K": "High"},
        "is_nitrogen_fixer": False,
        "root_depth": "Shallow (20-30 cm)",
        "drought_tolerance": "Low",
        "flood_tolerance": "High",
        "climate_sensitivity": "High to water shortage & extreme heat during flowering",
        "growing_season": "Kharif / Monsoon / Summer (100-150 days)",
        "rotation_benefits": "High caloric yield, stabilizes flooded lowland soils",
        "potential_risks": "High water depletion, builds up puddle compaction and methane emissions if monocultured",
        "description_en": "Primary staple cereal requiring substantial moisture and submerged or flooded conditions.",
        "description_bn": "প্রধান খাদ্যশস্য যা প্রচুর পানি ও আর্দ্র পরিবেশ পছন্দ করে। অতিরিক্ত একফসলি চাষে ভূগর্ভস্থ পানির চাপ বাড়ে।"
    },
    {
        "id": "wheat",
        "name": "Wheat",
        "bangla_name": "গম",
        "scientific_name": "Triticum aestivum",
        "category": "Cereal",
        "family": "Poaceae",
        "water_requirement_mm": 450,
        "water_level": "Medium",
        "temp_min": 12,
        "temp_max": 25,
        "optimal_temp": "15°C - 22°C",
        "soil_types": ["Loamy", "Clay", "Silty", "Mixed"],
        "soil_ph_range": [6.0, 7.5],
        "nutrient_demand": {"N": "High", "P": "Medium", "K": "Medium"},
        "is_nitrogen_fixer": False,
        "root_depth": "Medium (60-90 cm)",
        "drought_tolerance": "Medium",
        "flood_tolerance": "Low",
        "climate_sensitivity": "Terminal heat stress reduces grain fill window",
        "growing_season": "Rabi / Winter (100-120 days)",
        "rotation_benefits": "Moderate water demand, excellent staple winter crop following monsoon paddy",
        "potential_risks": "Vulnerable to unseasonal late-winter heat waves and waterlogging",
        "description_en": "Cool-season cereal staple that integrates well after summer rice with timely sowing.",
        "description_bn": "শীতকালীন দানাশস্য, আমন ধানের পর চাষের জন্য অত্যন্ত উপযোগী। অতিরিক্ত গরমে ফলন কমতে পারে।"
    },
    {
        "id": "maize",
        "name": "Maize (Corn)",
        "bangla_name": "ভুট্টা",
        "scientific_name": "Zea mays",
        "category": "Cereal",
        "family": "Poaceae",
        "water_requirement_mm": 600,
        "water_level": "Medium",
        "temp_min": 18,
        "temp_max": 34,
        "optimal_temp": "20°C - 30°C",
        "soil_types": ["Loamy", "Silty", "Sandy", "Mixed"],
        "soil_ph_range": [5.8, 7.2],
        "nutrient_demand": {"N": "High", "P": "High", "K": "High"},
        "is_nitrogen_fixer": False,
        "root_depth": "Deep (90-120 cm)",
        "drought_tolerance": "Medium",
        "flood_tolerance": "Low",
        "climate_sensitivity": "Sensitive to water deficit during silking and tasseling",
        "growing_season": "Rabi / Spring / Kharif (90-120 days)",
        "rotation_benefits": "Deep rooting loosens compact soil; high biomass residue for organic matter",
        "potential_risks": "Heavy feeder of nitrogen; requires rotation with nitrogen-fixing pulses",
        "description_en": "High-yielding versatile cereal with deep root architecture and strong industrial demand.",
        "description_bn": "উচ্চ ফলনশীল বহুমুখী ফসল। গভীর শিকড় মাটির শক্ত স্তর ভাঙে, তবে মাটিতে প্রচুর নাইট্রোজেন শোষণ করে।"
    },
    {
        "id": "lentil",
        "name": "Lentil",
        "bangla_name": "মসুর ডাল",
        "scientific_name": "Lens culinaris",
        "category": "Legume / Pulse",
        "family": "Fabaceae",
        "water_requirement_mm": 280,
        "water_level": "Low",
        "temp_min": 10,
        "temp_max": 26,
        "optimal_temp": "15°C - 24°C",
        "soil_types": ["Loamy", "Clay", "Sandy", "Mixed"],
        "soil_ph_range": [6.0, 8.0],
        "nutrient_demand": {"N": "Low (Fixes N)", "P": "Medium", "K": "Low"},
        "is_nitrogen_fixer": True,
        "root_depth": "Medium (50-70 cm)",
        "drought_tolerance": "High",
        "flood_tolerance": "Very Low",
        "climate_sensitivity": "Tolerates moisture deficit; highly susceptible to standing water",
        "growing_season": "Rabi / Winter (90-110 days)",
        "rotation_benefits": "Fixes 40-70 kg N/ha in soil, conserves irrigation water, breaks cereal disease cycles",
        "potential_risks": "Prone to collar rot and damping off if winter soil remains waterlogged",
        "description_en": "Champion low-water legume that fixes atmospheric nitrogen and enriches the soil.",
        "description_bn": "অল্প পানিতে চাষযোগ্য অত্যন্ত লাভজনক ডাল ফসল। বাতাস থেকে নাইট্রোজেন মাটিতে ধরে রাখে ও মাটির উর্বরতা বাড়ায়।"
    },
    {
        "id": "chickpea",
        "name": "Chickpea (Gram)",
        "bangla_name": "ছোলা",
        "scientific_name": "Cicer arietinum",
        "category": "Legume / Pulse",
        "family": "Fabaceae",
        "water_requirement_mm": 260,
        "water_level": "Low",
        "temp_min": 12,
        "temp_max": 30,
        "optimal_temp": "18°C - 26°C",
        "soil_types": ["Loamy", "Clay", "Silty", "Mixed"],
        "soil_ph_range": [6.0, 8.0],
        "nutrient_demand": {"N": "Low (Fixes N)", "P": "Medium", "K": "Low"},
        "is_nitrogen_fixer": True,
        "root_depth": "Deep (80-120 cm)",
        "drought_tolerance": "Very High",
        "flood_tolerance": "Very Low",
        "climate_sensitivity": "Excellent drought resilience; susceptible to frost and cloudiness during pod set",
        "growing_season": "Rabi / Winter (100-120 days)",
        "rotation_benefits": "Deep taproot extracts residual moisture; fixes 60-90 kg N/ha; minimizes synthetic fertilizer need",
        "potential_risks": "Susceptible to Ascochyta blight in unusually wet winters",
        "description_en": "Drought-hardy legume with deep taproots that mine subsoil moisture and naturally revitalize degraded land.",
        "description_bn": "খরা সহনশীল গভীর শিকড়যুক্ত ডাল ফসল। সাব-সয়েল থেকে আর্দ্রতা টানে এবং ইউরিয়া সারের খরচ নাটকীয়ভাবে কমায়।"
    },
    {
        "id": "soybean",
        "name": "Soybean",
        "bangla_name": "সয়াবিন",
        "scientific_name": "Glycine max",
        "category": "Legume / Oilseed",
        "family": "Fabaceae",
        "water_requirement_mm": 480,
        "water_level": "Medium",
        "temp_min": 18,
        "temp_max": 32,
        "optimal_temp": "22°C - 30°C",
        "soil_types": ["Loamy", "Clay", "Silty", "Mixed"],
        "soil_ph_range": [6.0, 7.0],
        "nutrient_demand": {"N": "Low (Fixes N)", "P": "Medium", "K": "Medium"},
        "is_nitrogen_fixer": True,
        "root_depth": "Medium (60-90 cm)",
        "drought_tolerance": "Medium",
        "flood_tolerance": "Low",
        "climate_sensitivity": "Needs balanced moisture during pod filling; sensitive to prolonged drought",
        "growing_season": "Kharif / Spring (90-115 days)",
        "rotation_benefits": "Powerhouse nitrogen fixer (fixes up to 100 kg N/ha); leaves nitrogen-rich organic leaf mulch",
        "potential_risks": "Pod shattering if harvested late during extreme dry spells",
        "description_en": "High-protein legume and oilseed that substantially enriches soil biological activity and nitrogen reserves.",
        "description_bn": "উচ্চ আমিষ ও তেলসমৃদ্ধ ডাল ফসল। মাটিতে বিপুল পরিমাণ জৈব নাইট্রোজেন যোগ করে মাটির স্বাস্থ্য উন্নত করে।"
    },
    {
        "id": "mustard",
        "name": "Mustard / Rapeseed",
        "bangla_name": "সরিষা",
        "scientific_name": "Brassica juncea",
        "category": "Oilseed",
        "family": "Brassicaceae",
        "water_requirement_mm": 240,
        "water_level": "Low",
        "temp_min": 10,
        "temp_max": 25,
        "optimal_temp": "14°C - 22°C",
        "soil_types": ["Loamy", "Sandy", "Clay", "Mixed"],
        "soil_ph_range": [6.0, 7.5],
        "nutrient_demand": {"N": "Medium", "P": "Medium", "K": "Low", "S": "High"},
        "is_nitrogen_fixer": False,
        "root_depth": "Medium (50-80 cm)",
        "drought_tolerance": "High",
        "flood_tolerance": "Low",
        "climate_sensitivity": "Sensitive to unseasonal rains and high aphid pressure during humid warm spells",
        "growing_season": "Short Rabi / Winter (75-90 days)",
        "rotation_benefits": "Short cycle fits perfectly between Rice and summer crops; biofumigant glucosinolates suppress soil nematodes",
        "potential_risks": "Requires adequate sulfur in soil for high oil content",
        "description_en": "Fast-maturing winter oilseed with natural biofumigation qualities that suppress soil-borne pathogens.",
        "description_bn": "স্বল্পমেয়াদী শীতকালীন তেল ফসল (৭৫-৯০ দিন)। মাটিতে কৃমি ও ক্ষতিকর ছত্রাক দমন করতে প্রাকৃতিকভাবে সাহায্য করে।"
    },
    {
        "id": "potato",
        "name": "Potato",
        "bangla_name": "আলু",
        "scientific_name": "Solanum tuberosum",
        "category": "Tuber / Cash Crop",
        "family": "Solanaceae",
        "water_requirement_mm": 500,
        "water_level": "Medium",
        "temp_min": 14,
        "temp_max": 24,
        "optimal_temp": "16°C - 20°C",
        "soil_types": ["Sandy", "Loamy", "Silty", "Mixed"],
        "soil_ph_range": [5.2, 6.5],
        "nutrient_demand": {"N": "High", "P": "High", "K": "High"},
        "is_nitrogen_fixer": False,
        "root_depth": "Shallow (30-50 cm)",
        "drought_tolerance": "Low",
        "flood_tolerance": "Very Low",
        "climate_sensitivity": "Sensitive to high night temperatures (>21°C inhibits tuberization) and late blight",
        "growing_season": "Rabi / Winter (85-105 days)",
        "rotation_benefits": "High economic return; improves soil tilth and aeration through ridging and bed work",
        "potential_risks": "Heavy nutrient extractor; requires rotation with legumes to avoid disease persistence",
        "description_en": "High-value tuber requiring well-aerated light soils and steady moisture for optimal tuber bulking.",
        "description_bn": "উচ্চমূল্যের অর্থকরী কন্দ ফসল। মাটির ভৌত গঠন উন্নত করে কিন্তু প্রচুর পটাশ ও পুষ্টি গ্রহণ করে।"
    },
    {
        "id": "sunflower",
        "name": "Sunflower",
        "bangla_name": "সূর্যমুখী",
        "scientific_name": "Helianthus annuus",
        "category": "Oilseed",
        "family": "Asteraceae",
        "water_requirement_mm": 400,
        "water_level": "Medium",
        "temp_min": 16,
        "temp_max": 34,
        "optimal_temp": "20°C - 28°C",
        "soil_types": ["Loamy", "Clay", "Sandy", "Mixed"],
        "soil_ph_range": [6.0, 7.5],
        "nutrient_demand": {"N": "Medium", "P": "Low", "K": "Medium"},
        "is_nitrogen_fixer": False,
        "root_depth": "Deep (120-180 cm)",
        "drought_tolerance": "High",
        "flood_tolerance": "Low",
        "climate_sensitivity": "High heat tolerance; deep taproot withstands dry spells",
        "growing_season": "Rabi / Spring / Summer (85-110 days)",
        "rotation_benefits": "Remarkable deep rooting extracts nutrients from subsoil horizons; provides pollinator habitat",
        "potential_risks": "Allelopathic residues can affect closely spaced sensitive subsequent seedlings if not tilled",
        "description_en": "Deep-rooted drought-resilient oilseed that scavenges nutrients leached deep into the subsoil.",
        "description_bn": "খরা সহনশীল গভীর মূলী তেলবীজ। মাটির গভীর থেকে পুষ্টি উপাদান টেনে আনে এবং মৌমাছির পরাগায়ন বৃদ্ধি করে।"
    },
    {
        "id": "groundnut",
        "name": "Groundnut / Peanut",
        "bangla_name": "চীনাবাদাম",
        "scientific_name": "Arachis hypogaea",
        "category": "Legume / Oilseed",
        "family": "Fabaceae",
        "water_requirement_mm": 420,
        "water_level": "Medium",
        "temp_min": 20,
        "temp_max": 34,
        "optimal_temp": "24°C - 30°C",
        "soil_types": ["Sandy", "Loamy", "Mixed"],
        "soil_ph_range": [5.8, 6.8],
        "nutrient_demand": {"N": "Low (Fixes N)", "P": "Medium", "K": "Low", "Ca": "High"},
        "is_nitrogen_fixer": True,
        "root_depth": "Medium (50-80 cm)",
        "drought_tolerance": "High",
        "flood_tolerance": "Low",
        "climate_sensitivity": "Tolerates high temperatures; requires friable soil for peg entry",
        "growing_season": "Kharif / Summer (100-130 days)",
        "rotation_benefits": "Excellent ground cover prevents soil erosion; fixes 50-80 kg N/ha; thrives in sandy soils",
        "potential_risks": "Aflatoxin mold risk if late harvest coincides with unexpected moisture stress",
        "description_en": "Sandy-soil specialist legume that protects against wind/water erosion while fixing biological nitrogen.",
        "description_bn": "বেলে ও বেলে-দোআঁশ মাটির জন্য আদর্শ ডাল-তেল ফসল। মাটির ক্ষয় রোধ করে এবং প্রাকৃতিকভাবে নাইট্রোজেন যুক্ত করে।"
    },
    {
        "id": "mungbean",
        "name": "Mungbean (Green Gram)",
        "bangla_name": "মুগ ডাল",
        "scientific_name": "Vigna radiata",
        "category": "Legume / Pulse",
        "family": "Fabaceae",
        "water_requirement_mm": 250,
        "water_level": "Low",
        "temp_min": 20,
        "temp_max": 36,
        "optimal_temp": "25°C - 32°C",
        "soil_types": ["Loamy", "Sandy", "Clay", "Mixed"],
        "soil_ph_range": [6.2, 7.5],
        "nutrient_demand": {"N": "Low (Fixes N)", "P": "Medium", "K": "Low"},
        "is_nitrogen_fixer": True,
        "root_depth": "Shallow to Medium (40-60 cm)",
        "drought_tolerance": "High",
        "flood_tolerance": "Low",
        "climate_sensitivity": "Heat-tolerant summer crop; vulnerable to continuous cloudy monsoon rain",
        "growing_season": "Summer / Late Rabi (60-75 days)",
        "rotation_benefits": "Ultra-short 65-day catch crop; fixes 30-50 kg N/ha; excellent green manure incorporation",
        "potential_risks": "Yellow mosaic virus if vector whiteflies are not managed",
        "description_en": "Ultra-fast maturing summer legume that slots into narrow fallow windows between major crop cycles.",
        "description_bn": "মাত্র ৬০-৭০ দিনে প্রস্তুত হওয়া চমৎকার ডাল ফসল। দুটি প্রধান ফসলের মধ্যবর্তী সময়ে চাষ করে মাটির উর্বরতা পুনরুদ্ধার করা যায়।"
    },
    {
        "id": "blackgram",
        "name": "Blackgram (Mashkalai)",
        "bangla_name": "মাষকলাই",
        "scientific_name": "Vigna mungo",
        "category": "Legume / Pulse",
        "family": "Fabaceae",
        "water_requirement_mm": 240,
        "water_level": "Low",
        "temp_min": 20,
        "temp_max": 35,
        "optimal_temp": "24°C - 32°C",
        "soil_types": ["Loamy", "Clay", "Mixed"],
        "soil_ph_range": [6.0, 7.5],
        "nutrient_demand": {"N": "Low (Fixes N)", "P": "Medium", "K": "Low"},
        "is_nitrogen_fixer": True,
        "root_depth": "Medium (50-70 cm)",
        "drought_tolerance": "High",
        "flood_tolerance": "Medium",
        "climate_sensitivity": "High heat tolerance; tolerates residual post-monsoon moisture well",
        "growing_season": "Late Kharif / Autumn (70-85 days)",
        "rotation_benefits": "Dense foliage smothers weeds; fixes substantial nitrogen; excellent relay crop in standing rice",
        "potential_risks": "Susceptible to powdery mildew during cooler late-season nights",
        "description_en": "Rugged pulse frequently broadcast as a relay crop directly into maturing rice fields without tilling.",
        "description_bn": "আমন ধানের জমিতে রিলে ফসল হিসেবে সহজে চাষযোগ্য। আগাছা দমন করে এবং মাটির স্বাস্থ্য রক্ষা করে।"
    },
    {
        "id": "barley",
        "name": "Barley",
        "bangla_name": "যব / বার্লি",
        "scientific_name": "Hordeum vulgare",
        "category": "Cereal",
        "family": "Poaceae",
        "water_requirement_mm": 320,
        "water_level": "Low",
        "temp_min": 10,
        "temp_max": 26,
        "optimal_temp": "14°C - 20°C",
        "soil_types": ["Sandy", "Loamy", "Clay", "Mixed"],
        "soil_ph_range": [6.5, 8.5],
        "nutrient_demand": {"N": "Medium", "P": "Low", "K": "Medium"},
        "is_nitrogen_fixer": False,
        "root_depth": "Deep (90-120 cm)",
        "drought_tolerance": "Very High",
        "flood_tolerance": "Low",
        "climate_sensitivity": "Exceptional saline and drought tolerance; outperforms wheat under water stress",
        "growing_season": "Rabi / Winter (90-110 days)",
        "rotation_benefits": "Tolerates higher soil salinity; requires significantly less water than wheat or rice",
        "potential_risks": "Lower market price per ton compared to wheat in some local markets",
        "description_en": "Salinity and drought-tolerant cereal that thrives on marginal lands where wheat yields fail.",
        "description_bn": "লবণাক্ত ও খরাপ্রবণ এলাকার জন্য সেরা শীতকালীন খাদ্যশস্য। গমের চেয়ে অনেক কম পানিতে ভালো ফলন দেয়।"
    },
    {
        "id": "sorghum",
        "name": "Sorghum (Jowar)",
        "bangla_name": "জোয়ার",
        "scientific_name": "Sorghum bicolor",
        "category": "Cereal / Millets",
        "family": "Poaceae",
        "water_requirement_mm": 350,
        "water_level": "Low",
        "temp_min": 18,
        "temp_max": 38,
        "optimal_temp": "24°C - 32°C",
        "soil_types": ["Clay", "Loamy", "Sandy", "Mixed"],
        "soil_ph_range": [5.5, 8.0],
        "nutrient_demand": {"N": "Medium", "P": "Medium", "K": "Low"},
        "is_nitrogen_fixer": False,
        "root_depth": "Very Deep (120-180 cm)",
        "drought_tolerance": "Very High",
        "flood_tolerance": "Medium",
        "climate_sensitivity": "Exceptional heat and drought tolerance; enters dormancy during extreme dry spells",
        "growing_season": "Kharif / Summer (90-110 days)",
        "rotation_benefits": "Extreme climate resilience; suppresses weed seedbank; massive carbon biomass input into soil",
        "potential_risks": "High C:N ratio crop residue decomposes slowly without nitrogen starter",
        "description_en": "The camel of crops: withstands scorching heat and protracted dry spells while preserving soil organic matter.",
        "description_bn": "তীব্র খরা ও তাপ সহনশীল দানাদার ফসল। মাটির গভীর থেকে পানি সংগ্রহ করে প্রতিকূল জলবায়ুতে টিকে থাকে।"
    },
    {
        "id": "finger_millet",
        "name": "Finger Millet (Ragi)",
        "bangla_name": "কাউন / বাজরা",
        "scientific_name": "Eleusine coracana",
        "category": "Millets",
        "family": "Poaceae",
        "water_requirement_mm": 300,
        "water_level": "Low",
        "temp_min": 16,
        "temp_max": 35,
        "optimal_temp": "22°C - 30°C",
        "soil_types": ["Sandy", "Loamy", "Clay", "Mixed"],
        "soil_ph_range": [5.0, 7.5],
        "nutrient_demand": {"N": "Low", "P": "Low", "K": "Low"},
        "is_nitrogen_fixer": False,
        "root_depth": "Medium (60-80 cm)",
        "drought_tolerance": "Very High",
        "flood_tolerance": "Low",
        "climate_sensitivity": "Nutritionally dense super-grain resilient to poor soil fertility and high climate variability",
        "growing_season": "Kharif / Summer (90-110 days)",
        "rotation_benefits": "Thrives on marginal degraded soils with minimal inputs; highly resilient to erratic rainfall",
        "potential_risks": "Slow early vegetative establishment requiring weed management",
        "description_en": "Climate-smart ancient grain packed with calcium and minerals, needing negligible synthetic inputs.",
        "description_bn": "পুষ্টিসমৃদ্ধ পরিবেশবান্ধব প্রাচীন খাদ্যশস্য। অতি সামান্য সার ও পানিতে প্রতিকূল আবহাওয়ায় টিকে থাকে।"
    },
    {
        "id": "jute",
        "name": "Jute",
        "bangla_name": "পাট",
        "scientific_name": "Corchorus olitorius",
        "category": "Fiber / Cash Crop",
        "family": "Malvaceae",
        "water_requirement_mm": 550,
        "water_level": "Medium",
        "temp_min": 22,
        "temp_max": 38,
        "optimal_temp": "25°C - 35°C",
        "soil_types": ["Loamy", "Clay", "Silty", "Mixed"],
        "soil_ph_range": [6.0, 7.5],
        "nutrient_demand": {"N": "Medium", "P": "Low", "K": "Medium"},
        "is_nitrogen_fixer": False,
        "root_depth": "Deep (90-120 cm)",
        "drought_tolerance": "Medium",
        "flood_tolerance": "High (Post-establishment)",
        "climate_sensitivity": "Loves hot humid monsoon conditions; tolerates temporary flooding once tall",
        "growing_season": "Kharif / Pre-monsoon (100-120 days)",
        "rotation_benefits": "Massive leaf fall (3-4 tonnes/ha) acts as natural green compost; loosens hard subsoil pans",
        "potential_risks": "Requires clean slow-moving water bodies for post-harvest retting",
        "description_en": "Golden fiber crop whose dense leaf fall replenishes topsoil organic carbon dramatically.",
        "description_bn": "সোনালী আঁশ ফসল। মৌসুমজুড়ে ঝরে পড়া প্রচুর পাতা প্রাকৃতিকভাবে মাটিতে জৈব সার তৈরি করে।"
    },
    {
        "id": "cotton",
        "name": "Cotton",
        "bangla_name": "তুলা",
        "scientific_name": "Gossypium hirsutum",
        "category": "Fiber / Cash Crop",
        "family": "Malvaceae",
        "water_requirement_mm": 650,
        "water_level": "Medium",
        "temp_min": 20,
        "temp_max": 38,
        "optimal_temp": "24°C - 32°C",
        "soil_types": ["Clay", "Loamy", "Mixed"],
        "soil_ph_range": [6.0, 8.0],
        "nutrient_demand": {"N": "High", "P": "Medium", "K": "High"},
        "is_nitrogen_fixer": False,
        "root_depth": "Deep (120-160 cm)",
        "drought_tolerance": "Medium",
        "flood_tolerance": "Low",
        "climate_sensitivity": "Needs long frost-free warm season; sensitive to heavy unseasonal rains during boll bursting",
        "growing_season": "Kharif / Summer (140-180 days)",
        "rotation_benefits": "Deep taproot channels subsoil moisture; high economic return",
        "potential_risks": "High pest vulnerability if grown continuously without rotation breaks",
        "description_en": "Deep-rooted commercial fiber crop that demands careful rotational disease management.",
        "description_bn": "অর্থকরী আঁশ ফসল। গভীর শিকড়ের মাধ্যমে মাটির নিচের পানি ব্যবহার করে তবে পোকার আক্রমণ রোধে শস্যাবর্তন আবশ্যক।"
    },
    {
        "id": "tomato",
        "name": "Tomato",
        "bangla_name": "টমেটো",
        "scientific_name": "Solanum lycopersicum",
        "category": "Vegetable",
        "family": "Solanaceae",
        "water_requirement_mm": 450,
        "water_level": "Medium",
        "temp_min": 15,
        "temp_max": 30,
        "optimal_temp": "18°C - 26°C",
        "soil_types": ["Loamy", "Sandy", "Mixed"],
        "soil_ph_range": [6.0, 6.8],
        "nutrient_demand": {"N": "Medium", "P": "High", "K": "High"},
        "is_nitrogen_fixer": False,
        "root_depth": "Medium (50-70 cm)",
        "drought_tolerance": "Low",
        "flood_tolerance": "Very Low",
        "climate_sensitivity": "High blossom drop at >32°C; susceptible to bacterial wilt and virus vectors",
        "growing_season": "Winter / Spring (75-95 days)",
        "rotation_benefits": "Rapid high-value cash flow; intensive management boosts soil tilth",
        "potential_risks": "Must never follow potato or eggplant (same Solanaceae family) due to soil pathogen carryover",
        "description_en": "High-value horticultural crop requiring strict rotation away from other nightshade family plants.",
        "description_bn": "উচ্চমূল্যের সবজি ফসল। একই জমিতে পরপর বেগুন বা আলুর সাথে চাষ করা নিষেধ যাতে ছত্রাক ও রোগ বিস্তার না ঘটে।"
    },
    {
        "id": "cowpea",
        "name": "Cowpea",
        "bangla_name": "বরবটি / ফেলন ডাল",
        "scientific_name": "Vigna unguiculata",
        "category": "Legume / Cover Crop",
        "family": "Fabaceae",
        "water_requirement_mm": 290,
        "water_level": "Low",
        "temp_min": 18,
        "temp_max": 36,
        "optimal_temp": "24°C - 32°C",
        "soil_types": ["Sandy", "Loamy", "Clay", "Mixed"],
        "soil_ph_range": [5.5, 7.5],
        "nutrient_demand": {"N": "Low (Fixes N)", "P": "Low", "K": "Low"},
        "is_nitrogen_fixer": True,
        "root_depth": "Deep (80-120 cm)",
        "drought_tolerance": "Very High",
        "flood_tolerance": "Low",
        "climate_sensitivity": "Exceptional heat and drought tolerance; fixes nitrogen even in nutrient-poor acidic soils",
        "growing_season": "Kharif / Summer (65-85 days)",
        "rotation_benefits": "Fixes 60-80 kg N/ha; broad foliage forms a living mulch reducing soil temperature and evaporative loss",
        "potential_risks": "Sensitive to waterlogged standing water in heavy clay soils",
        "description_en": "Resilient multi-purpose legume that provides edible pods while acting as a living thermal soil blanket.",
        "description_bn": "খরা ও তাপ সহনশীল চমৎকার ডাল ও সবজি। মাটির তাপমাত্রা কম রাখে এবং প্রচুর নাইট্রোজেন সংবন্ধন করে।"
    },
    {
        "id": "sesame",
        "name": "Sesame (Til)",
        "bangla_name": "তিল",
        "scientific_name": "Sesamum indicum",
        "category": "Oilseed",
        "family": "Pedaliaceae",
        "water_requirement_mm": 250,
        "water_level": "Low",
        "temp_min": 20,
        "temp_max": 38,
        "optimal_temp": "26°C - 34°C",
        "soil_types": ["Loamy", "Sandy", "Mixed"],
        "soil_ph_range": [5.5, 7.5],
        "nutrient_demand": {"N": "Low", "P": "Low", "K": "Low"},
        "is_nitrogen_fixer": False,
        "root_depth": "Deep (80-110 cm)",
        "drought_tolerance": "Very High",
        "flood_tolerance": "Very Low",
        "climate_sensitivity": "Thrives in dry hot climates; zero tolerance for standing water",
        "growing_season": "Summer / Late Rabi (80-95 days)",
        "rotation_benefits": "Minimal water use; deep roots scavenge nutrients; excellent oilseed for dry seasons",
        "potential_risks": "Seedling emergence is sensitive to heavy crusting rains",
        "description_en": "Extremely drought-tolerant oilseed requiring minimal moisture and thriving in high summer heat.",
        "description_bn": "অল্প খরচে চাষযোগ্য অতি খরা সহনশীল তেল ফসল। গ্রীষ্মের শুষ্ক মৌসুমে অত্যন্ত ফলপ্রসূ।"
    }
]

def get_crop_by_id(crop_id: str):
    for crop in CROPS_DATABASE:
        if crop["id"] == crop_id:
            return crop
    return None

def get_all_crops():
    return CROPS_DATABASE

